name: mobile_dashboard
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter   

  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  shared_preferences: ^0.5.12+4
  dartz: ^0.9.2
  google_fonts: ^1.1.2
  dio: ^3.0.10
  fl_chart: ^0.20.1
  get_it: any
  intl: any
  flutter_swiper: any
  postgres: any
  fluttertoast: ^7.1.8
  form_field_validator: ^1.1.0

dev_dependencies:
  build_runner: ^1.11.5
  mobx_codegen: ^1.1.2
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  change_app_package_name:
  flutter_launcher_name:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_foreground: 'assets/ic_launcher.png'
  adaptive_icon_background: '#2196f3'

flutter_launcher_name:
  name: "ChronosApp"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/

